# Generated by Django 3.1.5 on 2021-01-23 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('adress', models.TextField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.IntegerField()),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.TextField(max_length=255)),
                ('categories', models.ManyToManyField(related_name='donation', to='dary.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doninst', to='dary.institution')),
                ('user', models.ForeignKey(default='Null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
